  # Challenge

  ## Identifying Outliers using Standard Deviation

In [1]:
# initial imports
import pandas as pd
import numpy as np
import random
from sqlalchemy import create_engine

In [2]:
# create a connection to the database
engine = create_engine("postgresql://postgres:password@localhost:5432/Transaction")

In [3]:
# code a function to identify outliers based on standard deviation
query_1="Select holder.id,trn.amount from card_holder holder join credit_card card on holder.id=card.id_card_holder join transactions trn on trn.card=card.card"
transactions=pd.read_sql(query_1, engine)
elements=np.array(transactions.amount)
mean = np.mean(elements, axis=0)
sd = np.std(elements, axis=0)
cut_off = sd * 3
lower=  mean - cut_off
upper = mean + cut_off

In [4]:
# find anomalous transactions for 3 random card holders
outliers = [x for x in elements if x < lower or x > upper]
outliers_df = pd.DataFrame(data=outliers)
outliers_df

         0
0   1031.0
1   1685.0
2   1029.0
3   1131.0
4   1678.0
5   1691.0
6   1177.0
7   1430.0
8   1072.0
9   1839.0
10  1145.0
11  1119.0
12  1534.0
13  1617.0
14  1334.0
15  1530.0
16   852.0
17  1011.0
18  1009.0
19  1077.0
20  1063.0
21  1086.0
22  2108.0
23  1901.0
24  1046.0
25  1203.0
26  1814.0
27  1162.0
28   749.0
29  1795.0
..     ...
47  1790.0
48  1017.0
49  1056.0
50  1176.0
51  1856.0
52  1075.0
53  1095.0
54  1060.0
55   757.0
56  1179.0
57  1053.0
58  1911.0
59  1769.0
60  1054.0
61  1123.0
62  1802.0
63  1279.0
64  1660.0
65  1014.0
66  1894.0
67  1154.0
68  2249.0
69   748.0
70  1074.0
71  1296.0
72  1724.0
73  1301.0
74  1634.0
75  1035.0
76  1033.0

[77 rows x 1 columns]

  ## Identifying Outliers Using Interquartile Range

In [5]:
# code a function to identify outliers based on interquartile range
def outlier_treatment(datacolumn):
    sorted(datacolumn)
    Q1,Q3 = np.percentile(datacolumn , [25,75])
    IQR = Q3 - Q1
    lower_range = Q1 - (1.5 * IQR)
    upper_range = Q3 + (1.5 * IQR)
    return lower_range,upper_range

In [6]:
lowerbound,upperbound = outlier_treatment(transactions.amount)

In [7]:
# find anomalous transactions for 3 random card holders
transactions[(transactions.amount < lowerbound) | (transactions.amount > upperbound)]

      id  amount
15    12  1031.0
27     7  1685.0
53    18   175.0
62     6  1029.0
67    18   333.0
95    16   229.0
212   16  1131.0
219   12  1678.0
235    1  1691.0
296   25  1177.0
379    7   445.0
457   16  1430.0
484    7  1072.0
487   18  1839.0
563    6  1145.0
575    3  1119.0
613    9  1534.0
625   16  1617.0
636   25  1334.0
671    6   389.0
708   12  1530.0
795   12   852.0
797   24  1011.0
852    9  1009.0
911   25   100.0
925   18  1077.0
960   25  1063.0
979    1   283.0
982   25   269.0
991    7   543.0
...   ..     ...
2750   3   206.0
2786   1   484.0
2811   3  1053.0
2815  16   178.0
2861  16   393.0
2902  25   137.0
3064  24   466.0
3067  16  1911.0
3095  18  1769.0
3122   3  1054.0
3153  12   233.0
3171  12  1123.0
3183   1   267.0
3187  12  1802.0
3190   6  1279.0
3191   1  1660.0
3237  16  1014.0
3251   9    57.0
3263   1  1894.0
3324  18  1154.0
3327   7  2249.0
3331  12   748.0
3375  25  1074.0
3379   7  1296.0
3389   9  1724.0
3405  24  1301.0
3429  16  1634.0
3433  24  1035.0
3472   3   313.0
3492   1  1033.0

[110 rows x 2 columns]